Tesis/Apps/sosjujuy/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings

from . import views
from . import search

urlpatterns = [
    path('', views.index, name='index'),
    # buscadores
    path('search/', login_required(search.Search.as_view()), name='buscador'),
    path('provincias/', login_required(search.ProvinciaListado.as_view()), name='provincia'),
    path('beneficiariosearch/', login_required(search.BeneficiarioListado.as_view()), name='provincia'),
    path('prestadorsearch/', login_required(search.PrestadorListado.as_view()), name='buscador_prestador'),
    # find buscadores
    path('reportes/', views.reports, name='reports'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('domicilios/', login_required(views.DomicilioListView.as_view()), name='domicilio_changelist'),
    path('domicilio/', login_required(views.DomicilioCreateView.as_view()), name='domicilio_add'),
    path('domicilio/<int:pk>/', login_required(views.DomicilioUpdateView.as_view()), name='domicilio_change'),
    path('domiciliodelete/<domicilio_id>', login_required(views.deleteDomicilio), name='domicilio_delete'),
    path('beneficiarios/', login_required(views.BeneficiarioListView.as_view()), name='beneficiario_changelist'),
    path('beneficiario/', login_required(views.BeneficiarioCreateView.as_view()), name='beneficiario_add'),
    path('beneficiario/<int:pk>/', login_required(views.BeneficiarioUpdateView.as_view()), name='beneficiario_change'),
    path('beneficiarodelete/<beneficiario_id>', login_required(views.deleteBeneficiario), name='beneficiario_delete'),
    # notificaciones
    path('notificaciones/', login_required(views.NotificacionesListView.as_view()), name='notificacion_changelist'),
    path('notificacion/', login_required(views.NotificacionCreateView.as_view()), name='notificacion_add'),
    path('reporte/notificacion/', login_required(views.ReporteNotificacion.as_view()), name='reporte_notificacion'),
    path('notificacion/<int:pk>/', login_required(views.NotificacionUpdateView.as_view()), name='notificacion_change'),
    # fin notificaciones
    path('prestadores/', login_required(views.PrestadorListView.as_view()), name='prestador_changelist'),
    path('prestador/', login_required(views.PrestadorCreateView.as_view()), name='prestador_add'),
    path('prestador/<int:pk>/', login_required(views.PrestadorUpdateView.as_view()), name='prestador_change'),
    path('prestador/get/', login_required(search.PrestadorGetView.as_view()), name='prestador_get'),
    path('beneficiario/get/', login_required(search.BeneficiarioGetView.as_view()), name='beneficiario_get'),
    path('prestaciones/', login_required(views.PrestacionListView.as_view()), name='prestacion_changelist'),
    path('prestacion/', login_required(views.PrestacionCreateView.as_view()), name='prestacion_add'),
    path('prestacion/<int:pk>/', login_required(views.PrestacionUpdateView.as_view()), name='prestacion_change'),
    path('prestacion/eliminar/<int:pk>/', login_required(views.PrestacionDeleteView.as_view()), name='prestacion_delete'),
    path('derivaciones/', login_required(views.DerivacionListView.as_view()), name='derivacion_changelist'),
    path('derivacion/', login_required(views.DerivacionCreateView.as_view()), name='derivacion_add'),
    path('derivacion/<int:pk>/', login_required(views.DerivacionUpdateView.as_view()), name='derivacion_change'),
    path('derivacion/eliminar/<int:pk>/', login_required(views.DerivacionDeleteView.as_view()), name='derivacion_delete'),
    path('derivacion_pdf/<int:pk>/', login_required(views.DerivacionPDFView.as_view()), name='derivacion_pdf'),
    path('actividades_extension/', login_required(views.ActividadExtensionListView.as_view()), name='actividad_extension_changelist'),
    path('actividad_extension/', login_required(views.ActividadExtensionCreateView.as_view()), name='actividad_extension_add'),
    path('actividad_extension/<int:pk>/', login_required(views.ActividadExtensionUpdateView.as_view()), name='actividad_extension_change'),
    path('actividad_extensiondelete/<actividad_extension_id>', login_required(views.deleteActividadExtension), name='actividad_extension_delete'),
    path('encuesta_beneficiario/<int:pk_beneficiario>_<int:pk_derivacion>', views.EncuestaAtencionBeneficiarioCreateView.as_view(), name='encuesta_beneficiario_add'),
    path(r'report_builder/', include('report_builder.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tesis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Tesis.Apps.sosjujuy.urls'))
]

Tesis/Apps/sosjujuy/models.py
from django.db import models
from django.contrib.auth.models import User


NA, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO = range(-1, 7)
Dias = (
    (NA, '-'),
    (LUNES, 'Lunes'),
    (MARTES, 'Martes'),
    (MIERCOLES, 'Miércoles'),
    (JUEVES, 'Jueves'),
    (VIERNES, 'Viernes'),
    (SABADO, 'Sábado'),
    (DOMINGO, 'Domingo'),
)


NA, ODONTOLOGIA, INGLES, PSICOLOGIA = range(-1, 3)
Rubros = (
    (NA, '-'),
    (ODONTOLOGIA, 'Odontología'),
    (INGLES, 'Clases de Inglés'),
    (PSICOLOGIA, 'Psicología'),
)

DNI, LE, LC = range(-1, 2)
Tipo_Documento = (
    (DNI, 'Documento Único'),
    (LE, 'Libreta de Enrolamiento'),
    (LC, 'Libreta Cívica'),
)


class Pais(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class Provincia(models.Model):
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class Persona(models.Model):
    nombre = models.CharField(max_length=60)
    apellido = models.CharField(max_length=60)
    tipo_documento = models.IntegerField(choices=Tipo_Documento, default=DNI)
    documento = models.IntegerField()
    sexo = models.CharField(max_length=1)
    fecha_de_nacimiento = models.DateField()
    telefono = models.CharField(max_length=16, null=True)

    class Meta:
        abstract = True

    def nombre_completo(self):
        cadena = "{0}, {1}"
        return cadena.format(self.apellido, self.nombre)

    def __str__(self):
        return self.nombre_completo()


class Domicilio(models.Model):
    pais = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True)
    provincia = models.ForeignKey(Provincia, on_delete=models.SET_NULL, null=True)
    ciudad = models.CharField(max_length=60)
    barrio = models.CharField(max_length=60, null=True)
    calle = models.CharField(max_length=60)
    numero = models.CharField(max_length=60)
    piso = models.CharField(max_length=60, null=True, blank=True)
    departamento = models.CharField(max_length=60, null=True, blank=True)
    observaciones = models.CharField(max_length=100, null=True, blank=True)

    def domicilio_completo(self):
        cadena = "{0}, {1} - {2} {3}"
        return cadena.format(self.provincia, self.ciudad, self.calle, self.numero)

    def __str__(self):
        return self.domicilio_completo()


class Antecedente(models.Model):
    enfermedad = models.CharField(max_length=60)
    fecha_aparicion = models.DateField()
    medicamento = models.CharField(max_length=60)


class Beneficiario(Persona):
    domicilio_legal = models.ForeignKey(Domicilio, on_delete=models.SET_NULL, blank=True, null=True,
                                        related_name='domicilio_legal')
    domicilio_real = models.ForeignKey(Domicilio, on_delete=models.SET_NULL, blank=True, null=True,
                                       related_name='domicilio_real')
    antecedente = models.ForeignKey(Antecedente, on_delete=models.SET_NULL, blank=True, null=True)
    familiar = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, default=None)
    email = models.EmailField(max_length=70, default='')


class Prestador(Persona):
    matricula = models.IntegerField()
    especialidad = models.CharField(max_length=300)


class Disponibilidad_horaria(models.Model):
    dia_de_la_semana = models.IntegerField(choices=Dias, default=NA)
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()


class Prestacion(models.Model):
    rubro = models.CharField(max_length=300)
    dias_disponibles = models.ForeignKey(Disponibilidad_horaria, on_delete=models.SET_NULL, blank=True, null=True)
    domicilio = models.ForeignKey(Domicilio, on_delete=models.SET_NULL, blank=True, null=True)
    porcentaje_de_cobertura = models.PositiveIntegerField()
    prestador = models.ForeignKey(Prestador, on_delete=models.SET_NULL, blank=True, null=True)
    descripcion = models.CharField(max_length=300)
    condiciones_de_prestacion = models.CharField(max_length=300)
    aclaraciones = models.CharField(max_length=300)

    def prestacion_completo(self):
        cadena = "{0}: {1}"
        return cadena.format(self.rubro, self.prestador)

    def __str__(self):
        return self.prestacion_completo()


class Notificacion(models.Model):
    escala = models.CharField(max_length=300)
    escalaDos = models.CharField(max_length=300)
    asunto = models.CharField(max_length=300)
    fecha = models.DateTimeField(auto_now_add=True)
    prestador = models.ForeignKey(Prestador, on_delete=models.SET_NULL, blank=True, null=True)
    beneficiario = models.ForeignKey(Beneficiario, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, models.SET_NULL, blank=True,null=True)
    def __str__(self):
        cadena = "{0}, {1}"
        return cadena.format(self.asunto, self.escala)


class NotificacionEstado(models.Model):
    notificacion = models.ForeignKey(Notificacion, on_delete=models.SET_NULL, blank=True, null=True)
    estado = models.CharField(max_length=300)
    observacion = models.CharField(max_length=500)
    archivo = models.FileField(max_length=254, null=True, blank=True)
    user = models.ForeignKey(User, models.SET_NULL, blank=True,null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        cadena = "{0}, {1}"
        return cadena.format(self.estado, self.observacion)


class ActividadExtension(models.Model):
    titulo = models.CharField(max_length=60)
    descripcion = models.CharField(max_length=300)
    fecha = models.DateTimeField()
    presupuesto = models.PositiveIntegerField()
    disertante = models.ForeignKey(Prestador, on_delete=models.SET_NULL, blank=True, null=True)
    capacidad = models.PositiveIntegerField()


class Derivacion(models.Model):
    beneficiario = models.ForeignKey(Beneficiario, on_delete=models.CASCADE)
    fecha_hora = models.DateTimeField(null=True)
    motivo = models.CharField(max_length=300)
    prestacion = models.ForeignKey(Prestacion, on_delete=models.CASCADE)
    observacion = models.CharField(max_length=300)

    def derivacion_completo(self):
        cadena = "{0} el día {1}/{2} a las {3} hs"
        if self.fecha_hora:
            return cadena.format(self.prestacion, self.fecha_hora.date.day, self.fecha_hora.date.month, self.fecha_hora.time)
        else:
            return "{0}".format(self.prestacion)

    def __str__(self):
        return self.derivacion_completo()


class EncuestaAtencionBeneficiario(models.Model):
    beneficiario = models.ForeignKey(Beneficiario, on_delete=models.SET_NULL, blank=True, null=True)
    derivacion = models.ForeignKey(Derivacion, on_delete=models.SET_NULL, blank=True, null=True)
    atendido = models.BooleanField()
    nivel_de_atencion = models.IntegerField(choices=[(x, x) for x in range(1, 6)], default=0)
    nivel_de_puntualidad = models.IntegerField(choices=[(x, x) for x in range(1, 6)], default=0)
    observacion = models.CharField(max_length=300)

Tesis/Apps/sosjujuy/templates/sosjujuy/actividadextension_form.html
{% extends "sosjujuy/base_site.html" %}

{% block content %}
    <div class="right_col" role="main">

        <form method="post" id="actividadExtensionForm" novalidate>
            <div class="">
                <div class="page-title">
                    <div class="col-md-4">
                        <h3>Registrar Actividad de Extensión</h3>
                    </div>
                </div>
                </br>
                <div class="clearfix"></div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="col-md-11" align="right">
                            <div class="x_panel border-aero">
                                <div class="x_title border-dark dark" align="center"><b>> Datos de la Actividad de Extensión <</b></div>
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="row">
                                        <div class="col-md-4" align="left" style="margin-top:8px">{{ form.field }}
                                            {{ field.label_tag }}
                                        </div>
                                        <div class="col-md-5 " style="margin-bottom: 5px">
                                            {{ field }}
                                            <a style="color:red">{{ field.errors }} </a>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>

                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4" align="right"><img src="/static/images/sosjujuy_index.jpg"></div>
                </div>
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class=" col-md-6">

                        <button type="submit" class="btn btn-primary col-md-3 border-dark"><b>Guardar</b></button>
                        <a href="{% url 'actividad_extension_changelist' %}" class="btn btn-danger col-md-3 border-dark">Cancelar</a>
                    </div>
                </div>
                <script>
                    function checkPositiveInt(value, field) {

                        var mensaje = "";

                        // comprobar los posibles errores
                        if ("" === this.value) {
                            mensaje = "El email no puede estar vacío";
                        } else if (this.value.indexOf("@") < 0) {
                            mensaje = "El email debe contener una @";
                        } else if (this.value.indexOf(".com", this.value.indexOf("@")) < 0) {
                            mensaje = "El email debe contener .com detras de la @";
                        }

                        // mostrar/resetear mensaje (el mensaje se resetea poniendolo a "")
                        this.setCustomValidity(mensaje);
                    }
                </script>
            </div>
        </form>
    </div>
{% endblock content %}

Tesis/Apps/sosjujuy/templates/sosjujuy/base_site.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      {% block headjavascripts %}
        <link rel="stylesheet" href="/static/build/css/prism.css">
        <link rel="stylesheet" href="/static/build/css/chosen.css">
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js">
        </script>
        <!-- bootstrap-datetimepicker -->
        <script src="/static/vendors/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
      {% endblock headjavascripts %}

      <title>SosJujuy | {% block title %}{% endblock %}</title>
      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- bootstrap-datetimepicker -->
        <link href="/static/vendors/bootstrap-datetimepicker/css/datetimepicker.css" rel="stylesheet">
        <link href="/static/vendors/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom.css" rel="stylesheet">
      <script type="text/javascript">
        var pagina = window.location.pathname;
        var goTo = JSON.parse(localStorage.getItem('goTo'));
        //
        if (pagina == "/prestadores/" || pagina == "/beneficiarios/" ){
          //window.location.replace("/notificaciones/");
          if (goTo["goTo"] == "/notificacion/"){
            window.location.replace("/notificacion/");
          } 
        }
      </script>
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">

    {% block body %}
    {% csrf_token %}


      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "sosjujuy/sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "sosjujuy/top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "sosjujuy/footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/chosen.jquery.js" type="text/javascript" charset="utf-8"></script>
      <script src="/static/build/js/prism.js" type="text/javascript" charset="utf-8"></script>
      
      <script src="/static/build/js/custom.js"></script>
      <script src="/static/build/js/index.js"></script>
      <script src="/static/build/js/estados_notificaciones.js"></script>
      <script type="text/javascript">
        var pagina = window.location.pathname;
        var goTo = JSON.parse(localStorage.getItem('goTo'));
        // 
        if (pagina == "/prestador/" && (goTo["goTo"] == "/notificacion/")){
          $(".page-title").find("h3").empty().append("<a href='/notificacion/'>Registrar Notificaciones ></a> Registrar Prestador");
        };
        if (pagina == "/beneficiario/" && (goTo["goTo"] == "/notificacion/")){
          $(".page-title").find("h3").empty().append("<a href='/notificacion/'>Registrar Notificaciones ></a> Registrar Beneficiario");
        };
      </script>
    {% endblock body %}
  </body>
</html>

Tesis/Apps/sosjujuy/templates/sosjujuy/derivacion_delete.html
{% extends "sosjujuy/base_site.html" %}

{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Eliminar Derivación</h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <form method="post">
                    {% csrf_token %}
                    <h3>¿Desea eliminar el registro?</h3>
                    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                    <a class= "btn btn-default" href="{% url 'derivacion_changelist' %}">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

Tesis/Apps/sosjujuy/templates/sosjujuy/domicilio_list.html
{% extends "sosjujuy/base_site.html" %}

{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <div class="col-md-6"><h3>Domicilios
                        </br>
                        <form action="{% url 'domicilio_add' %}">
                            <button type="submit" class = "btn btn-primary">Registrar NUEVO</button>
                        </form>
                    </h3>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-6"><h3>Domicilios Registrados</h3>
                    <table class="table table-bordered table-responsive">
                        {% for domicilio in object_list %}
                        <tr>
                            <th class="col-md-8"><h4>{{ domicilio }}</h4></th>
                            <th class="col-md-2"><a class="btn btn-success" href="{% url 'domicilio_change' domicilio.id %}">EDITAR</a></th>
                            <th class="col-md-2"><a class="btn btn-danger" href="{% url 'domicilio_delete' domicilio.id %}">BORRAR</a></th>
                        </tr>
                    {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

Tesis/Apps/sosjujuy/templates/sosjujuy/footer.html
<div class="pull-right">
  Realizado por el grupo 6 de la cátedra de Proyecto Final, año 2018, <a href="http://www.frc.utn.edu.ar/">UTN FRC</a>
</div>
<div class="clearfix"></div>

Tesis/Apps/sosjujuy/templates/sosjujuy/notificacion_seguimiento_datos.html
 <!--  Observacion, Archivo  -->

    <div class="row">
        <div class="col-md-6">
            <div class="col-md-4" style="text-align: left;">
                <strong>N° Notificación:</strong>
            </div>
            <div class="col-md-8 info" style="text-align: left;">
                {{ datos.id }}
            </div>
            <div class="clearfix">&nbsp;</div>
        </div>
        <div class="col-md-6">
            <div class="col-md-4" style="text-align: left;">
                <strong>Asunto:</strong>
            </div>
            <div class="col-md-8 info" style="text-align: left;">
                {{ datos.asunto }}
            </div>
        </div>
    </div>
    
    <!--  Escala, Escala2  -->
    <div class="row">
        <div class="col-md-6">
            <div class="col-md-4" style="text-align: left;">
                <strong>Escala1:</strong>
            </div>
            <div class="col-md-8 info" style="text-align: left;">
                {{ datos.escala }}
            </div>
            <div class="clearfix">&nbsp;</div>
        </div>
        <div class="col-md-6">
            <div class="col-md-4" style="text-align: left;">
                <strong>Escala2:</strong>
            </div>
            <div class="col-md-8 info" style="text-align: left;">
                {{ datos.escalaDos }}
            </div>
        </div>
    </div>
    <hr>
    <div style="text-align: center;"><h2>Observaciones</h2></div>
    <div style="padding: 1rem; height: 300px;overflow-y: scroll;" >
        {% for field in observaciones %}
            <div class="row">
                <div class="col-md-12" align="left" style="">
                    <p>Usuario: <span style="color: green">{{ field.user|title }} {{ field.user.last_name }}</span> | Fecha: {{ field.fecha }}</p>
                    <p>Observaciones: {{ field.observacion }}</p>
                    <p>Estado: <span style="color: red">{{ field.estado }}</span> | 
                    Adjunto: <a href="/media/{{ field.archivo }}">{{ field.archivo }}</a></p>
                    <div style="width: 100%;border-bottom: 1px dashed red"></div>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr>
    <!--  Prestador, Beneficiario  -->
    <div class="row">
        {% if datos.prestador.nombre %}
        <div class="col-md-6">
            <div class="col-md-6" style="text-align: center;">
                <hr>
                <h2>Prestador</h2>
                <hr>
            </div>
            <div class="clearfix">&nbsp;</div>
        </div>
        {% endif %}
        {% if datos.beneficiario.nombre %}
        <div class="col-md-6">
            <div class="col-md-6" style="text-align: center;">
                <hr>
                <h2>Beneficiario:</h2>
                <hr>
            </div>
            <div class="clearfix">&nbsp;</div>
        </div>
        {% endif %}
    </div>

    <!--  Prestador, Beneficiario  -->
    <div class="row">
        {% if datos.prestador.nombre %}
            <div class="col-md-6">
                <div class="col-md-8" style="margin-top: 1rem">
                    <div class="col-md-4" >
                        <label for="id_escala">Nombre:</label>
                    </div>
                    <div class="col-md-4" style="text-align: left;">
                        {{datos.prestador.nombre|title}}
                    </div>
                </div>
                <div class="col-md-1"></div>
                <div class="col-md-8" style="margin-top: 1rem">
                    <div class="col-md-4">
                        <label for="id_escala">Apellido:</label>
                    </div>
                    <div class="col-md-4" style="text-align: left;">
                        {{datos.prestador.apellido|title}}
                    </div>
                </div>
                <div class="col-md-1"></div>
                <div class="col-md-8" style="margin-top: 1rem">
                    <div class="col-md-4">
                        <label for="id_escala">Documento:</label>
                    </div>
                    <div class="col-md-4" style="text-align: left;">
                        {{datos.prestador.documento}}
                    </div>
                </div>
                <div class="col-md-4"></div>
                <div class="col-md-8" style="margin-top: 1rem">
                    <div class="col-md-4">
                        <label for="id_escala">Matricula:</label>
                    </div>
                    <div class="col-md-4" style="text-align: left;">
                        {{datos.prestador.matricula}}
                    </div>
                </div>
            </div>
        {% endif %}
        {% if datos.beneficiario.nombre %}
            <div class="col-md-6">
                <div class="col-md-8" style="margin-top: 1rem">
                    <div class="col-md-4">
                        <label for="id_escala">Nombre:</label>
                    </div>
                    <div class="col-md-4" style="text-align: left;">
                        {{datos.beneficiario.nombre|title}}
                    </div>
                </div>
                <div class="col-md-8" style="margin-top: 1rem">
                    <div class="col-md-4">
                        <label for="id_escala">Apellido:</label>
                    </div>
                    <div class="col-md-4" style="text-align: left;">
                        {{datos.beneficiario.apellido|title}}
                    </div>
                </div>
                <div class="col-md-8" style="margin-top: 1rem">
                    <div class="col-md-4" >
                        <label for="id_escala">Documento:</label>
                    </div>
                    <div class="col-md-4" style="text-align: left;">
                        {{datos.beneficiario.documento}}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>                                